### ISSUE TITLE
Is C++ client library available somewhere ?

### ISSUE THREAD

**Issue by MishaOrelKodiak** [epigramai/tfserving_predict_client#12]
There is no issue, just a question.

**Comment by johanjk** [comment]
Tf-serving uses grpc for communication, so one could make clients in any language supported by grpc, including c++. 
Some quick googling resulted in e.g. https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/resnet_client.cc

**Comment by MishaOrelKodiak** [comment]
Thanks johanjk.
I meant C++ client that, just like your client, does not depend on TF library.

**Comment by johanjk** [comment]
Not had to interface with tfserving myself from C++, so not looked into it much, but some more googling yielded: https://github.com/andrew-k-21-12/tf-serving-client-cpp
